debug: false
uuid: 87c8beee-6a65-4567-8859-0d78ad109114
token_id: gnYiWdknRM0xXMlS
token: ASSnZsbWOxPqt44l3UZv2yy9HQwcP3WxuMZXUbvcPDdvWN1bS7ZCKwiK4YrINsRF
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/devbotz.mahirmandala.my.id/fullchain.pem
    key: /etc/letsencrypt/live/devbotz.mahirmandala.my.id/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/Jexactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://my-panelkuu.devbotz.my.id'
