debug: false
uuid: 457b4670-52f4-4000-9d7c-139e79c12898
token_id: deSCTeX0ZPHG6Eau
token: W1uDTzh5QoR1rySJEoWucwtcSrHdKMmGtNWaQvDMPd0pQ0M2WYawfxeBAvC1Evej
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/node.devbotz.my.id/fullchain.pem
    key: /etc/letsencrypt/live/node.devbotz.my.id/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/Jexactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://my-panelkuu.devbotz.my.id'
