debug: false
uuid: a03aa13b-ba4e-4937-93bd-dd91511f5205
token_id: MVWM9BNUMLV88Jec
token: X347S6fJDEbxzPT2o69KEEsrRWo0nIotauxoh6H1vV257P2CIScLcOON98uFAmxq
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/node.skyofc.biz.id/fullchain.pem
    key: /etc/letsencrypt/live/node.skyofc.biz.id/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/Jexactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://my-panel.skyofc.biz.id'
