debug: false
uuid: cdfcf94f-8a0f-447b-9b8b-1829d58f5e31
token_id: B8SYJIIz2ZHypQ71
token: l9Ma4zRrz2dIWu2mlfD9iBU1SepBAZO0rESLiNCNQajcjz2g7vMnqkB2Nj6oX6V6
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/node.skyofc.biz.id/fullchain.pem
    key: /etc/letsencrypt/live/node.skyofc.biz.id/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/Jexactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://my-panel.skyofc.biz.id'
